<table class='datalist'>
	<thead class='datalist-head'>
		<tr class='group-count-row'>
			<th class='group-count' colspan=3></th>
		</tr>
		<tr class='title-row'>
			<th class='s-index' s-index='label'>标题</th>
			<th>文章数据分类</th>
			<th></th>
		</tr>
		<tr class='search-row'>
			<th><input class='q-index' q-index='label' type='text' name='' value='' /></th>
			<th><select class='q-index' q-index='groupId' name='groupId'>
				<?php echo $this->selectOptions($this->optVal, array('' => '[All Aticles]'))?>
			</select></th>
			<th><div class='query-invoker' class='button'>Search</div></th>
		</tr>
	</thead>
	<tbody class='datalist-body'>
	</tbody>
	<tfoot class='datalist-foot'>
		<tr class='paginator-row'><td id='datalist-paginator' colspan=3></td></tr>
		<tr class='bulk-action-row'><th class='group-count' colspan=3></th></tr>
	</tfoot>
</table>

<script>
	window.restUrl = '/adminrest/adminrest-article.json'
</script>

<script type='text/template' id='data-row'>
<td>
	{{data.label}}
</td>
<td>
	{{data.groupId}}
</td>
<td>
	<a href='/admin/article/edit/id/{{data.id}}'>编辑</a>
	<a class='ajax-to-trash' data-id='{{data.id}}' href='/admin/article/delete/id/{{data.id}}'>放入回收站</a>
</td>
</script>

<script type='text/template' id='data-trash-row'>
<td>
	{{data.label}}
</td>
<td>
	{{data.groupId}}
</td>
<td>
	<a class='ajax-to-trash' data-id='{{data.id}}' href='/admin/article/delete/id/{{data.id}}'>还原</a>
</td>
</script>

<script data-main="<?=$this->siteConfig('extUrl')?>/app/dataV4" src="<?=$this->siteConfig('extUrl')?>/require-jquery.js"></script>
