<div class='toolbar'>
	<div class='main'>
		<ul class='left'>
			<?php foreach($this->toolbar as $node) { if(isset($node['children'])) { ?>
			<li class='root parent'>
				<div class='mini-icon-bg mini-icon-arrow arrow'></div>
				<a class='root parent' href='<?php echo $node['url']?>'><?php echo $node['title'] ?></a>
				<ul class='child'>
				<?php foreach($node['children'] as $childNode) { ?>
		    		<li><a href='<?php echo $childNode['url']?>' ><?php echo $childNode['title']?></a></li>
		    	<?php } ?>
				</ul>
		    </li>
			<?php } else { ?>
			<li class='root'><a class='root' href='<?php echo $node['url']?>'><?php echo $node['title'] ?></a></li>
			<?php }} ?>
		</ul>
	</div>
	<div class='sub'>
	
	</div>
</div>