<table class='datalist'>
	<thead class='datalist-head'>
		<tr class='group-count-row'>
			<th class='group-count' colspan=3></th>
		</tr>
		<tr class='title-row'>
			<th class='s-index' s-index='email'>注册邮箱</th>
			<th class='s-index' s-index='userGroup'>用户权限分组</th>
			<th></th>
		</tr>
		<tr class='search-row'>
			<th><input class='q-index' q-index='email' type='text' name='' value='' /></th>
			<th><input class='q-index' q-index='userGroup' type='text' name='' value='' /></th>
			<th><div class='query-invoker' class='button'>Search</div></th>
		</tr>
	</thead>
	<tbody class='datalist-body'>
	</tbody>
	<tfoot class='datalist-foot'>
		<tr class='paginator-row'><td id='datalist-paginator' colspan=3></td></tr>
		<tr class='bulk-action-row'><th class='group-count' colspan=3></th></tr>
	</tfoot>
</table>

<script>
	window.restUrl = '/adminrest/userrest-user.json'
</script>

<script type='text/template' id='data-row'>
<td>
	{{data.email}}
</td>
<td>
	{{data.userGroup}}
</td>
<td>
	<a href='/admin/useradmin-user/edit/id/{{data.id}}'>编辑</a>
</td>
</script>

<script data-main="<?=$this->siteConfig('extUrl')?>/app/data" src="<?=$this->siteConfig('extUrl')?>/require-jquery.js"></script>
