<script type="text/javascript" src="<?=Class_Server::extUrl()?>/src/underscore.1.3.1.min.js"></script>
<script type="text/javascript" src="<?=Class_Server::extUrl()?>/src/backbone.0.9.1.min.js"></script>
<link	type="text/css"			href="http://minify.enorange.cn/?b=resource/cms/v2/admin/style&f=structure.css,front.css" media="screen" rel="stylesheet">
<!--  script type="text/javascript"	src="http://minify.enorange.cn/?b=resource&f=ext/func.js,ext/jquery.ndd.js,cms/v2/script/front.js,cms/v2/script/lightbox.js,cms/v2/script/links.js,cms/v2/script/bootstrap.js,cms/v2/script/icon-selector.js"></script -->
<script type="text/javascript"	src="http://lib.eo.test/ext/func.js"></script>
<script type="text/javascript"	src="http://lib.eo.test/ext/jquery.ndd.js"></script>
<script type="text/javascript"	src="http://lib.eo.test/cms/v3/script/front.js"></script>
<script type="text/javascript"	src="http://lib.eo.test/cms/v3/script/lightbox.js"></script>
<script type="text/javascript"	src="http://lib.eo.test/cms/v3/script/bootstrap.js"></script>
<script type="text/javascript"	src="http://lib.eo.test/cms/v3/script/icon-selector.js"></script>

<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/brick/action-menu/action-menu.front.js"></script>
<link href="<?=Class_Server::extUrl()?>/brick/action-title/action-title.css" media="screen" rel="stylesheet" type="text/css" >
<link href="<?=Class_Server::extUrl()?>/brick/action-menu/action-menu.css" media="screen" rel="stylesheet" type="text/css" >

<script type="text/javascript"	src="<?=Class_Server::extUrl()?>/ckeditor/ckeditor.js"></script>
<script>
/************************************/
/*Declear Global Javascript Items****/
/************************************/
var LAYOUT_STAGE_CHANGED = false;
var CURR_STATUS;
var STAGE_ID;
var SPRITE_NAME;
var MINI_BRICK_MASK;

var WB;
var FINDER;
var EventMessenger = {};
_.extend(EventMessenger, Backbone.Events);

window.ORG_CODE = "<?php echo Class_Server::getOrgCode()?>";
window.SITE_FOLDER = "<?php echo Class_Server::getSiteFolder()?>";
</script>