<?php echo $this->tabForm($this->form, array()); ?>

<?php if($this->editor == 'cm') { ?>
<?php $this->headScript()->appendFile($this->siteConfig('extUrl').'/codemirror/codemirror.js');?>
<?php $this->headScript()->appendFile($this->siteConfig('extUrl').'/codemirror/mode/xml.js');?>
<?php $this->headScript()->appendFile($this->siteConfig('extUrl').'/codemirror/mode/javascript.js');?>
<?php $this->headScript()->appendFile($this->siteConfig('extUrl').'/codemirror/mode/css.js');?>
<?php $this->headScript()->appendFile($this->siteConfig('extUrl').'/codemirror/htmlmixed.js');?>
<?php $this->headLink()->appendStylesheet($this->siteConfig('extUrl').'/codemirror/codemirror.css');?>
<script>
var editor = document.getElementById('codemirror-editor');
if(editor != null) {
	codeMirrorEditor = CodeMirror.fromTextArea(editor, {
		lineNumbers: true,
		matchBrackets: true,
		indentUnit: 4,
		indentWithTabs: true,
		dragDrop: false,
		onBlur: function() {
			codeMirrorEditor.save();
		}
	});
	codeMirrorEditor.focus();
}
</script>
<?php } ?>