<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class DocumentServiceAccountDomainHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['domainName'])) {
            $value = $data['domainName'];
            $return = (string) $value;
            $this->class->reflFields['domainName']->setValue($document, $return);
            $hydratedData['domainName'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['isActive'])) {
            $value = $data['isActive'];
            $return = (bool) $value;
            $this->class->reflFields['isActive']->setValue($document, $return);
            $hydratedData['isActive'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['isDefault'])) {
            $value = $data['isDefault'];
            $return = (bool) $value;
            $this->class->reflFields['isDefault']->setValue($document, $return);
            $hydratedData['isDefault'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['redirect'])) {
            $value = $data['redirect'];
            $return = (string) $value;
            $this->class->reflFields['redirect']->setValue($document, $return);
            $hydratedData['redirect'] = $return;
        }
        return $hydratedData;
    }
}