<table class='datalist'>
	<thead class='datalist-head'>
		<tr class='title-row'>
			<th class='s-index' s-index='_id' style='width: 100px;'>ID</th>
			<th class='s-index' s-index='label' style='width: 285px;'>产品名</th>
			<th class='s-index' s-index='name' style='width: 285px;'>产品型号编码</th>
			<th></th>
		</tr>
		<tr class='search-row'>
			<th><input class='q-index' q-index='_id' type='text' name='' value='' /></th>
			<th><input class='q-index' q-index='label' type='text' name='' value='' /></th>
			<th><input class='q-index' q-index='name' type='text' name='' value='' /></th>
			<th><div class='query-invoker' class='button'>Search</div></th>
		</tr>
	</thead>
	<tbody class='datalist-body'>
	</tbody>
	<tfoot class='datalist-foot'>
		<tr><td id='datalist-paginator' colspan='4'>
		</td></tr>
	</tfoot>
</table>

<script>
	window.restUrl = '/rest/product.json'
</script>

<script type='text/template' id='data-row'>
<td>
	{{data.id}}
</td>
<td>
	{{data.label}}
</td>
<td>
	{{data.name}}
</td>
<td>
	<a href='/admin/product/edit/id/{{data.id}}'>编辑</a>
</td>
</script>


<script data-main="<?=Class_Server::extUrl()?>/app/data" src="<?=Class_Server::extUrl()?>/require-jquery.js"></script>
